config/routes.rb
Bankio::Application.routes.draw do
  resources :transactions

  get "csv/import"
  post "csv/import" => 'csv#upload'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/csv_controller.rb
require 'fastercsv'
class CsvController < ApplicationController
	def import
	end

	def upload
		debugger
		FasterCSV.parse(params[:upload][:csv].tempfile) do |cells|
			@transaction = Transaction.new(
				:when => cells[0],
				:amount => cells[1],
				:description => cells[2],
				:total => cells[3]
				)
			@transaction.save
		end
		# While under development, just respond by rendering some in-line text.
		# Send back the request parameters in JSON (JavaScript Object Notation)
		# format, i.e. something reasonably easy to parse with the human eye.
		# render :text => params.to_json
		redirect_to transactions_path
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/csv/import.html.haml
= form_for :upload, :html => { :multipart => true } do |f|
	= f.file_field :csv
	= f.submit "Upload", :disable_with => 'Uploading...'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = csrf_meta_tag
    /[if lt IE 9]
      = javascript_include_tag 'html5'
  %body
    = yield
    = javascript_include_tag :defaults

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  -if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :when
    = f.date_select :when
  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :total
    = f.text_field :total
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th When
    %th Amount
    %th Description
    %th Total
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.when
      %td= transaction.amount
      %td= transaction.description
      %td= transaction.total
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b When:
  = @transaction.when
%p
  %b Amount:
  = @transaction.amount
%p
  %b Description:
  = @transaction.description
%p
  %b Total:
  = @transaction.total

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path